openapi: '3.0.0'
info:
  title: 'Alun Delivery API(s)'
  version: '1.0.0'
  description: >-
    Alun Delivery Courier API Documentation. 

paths:
  "/api/health":
    get:
      tags:
      - Monitor Health

      operationId: monitorHealth
      summary: Get health status of app
      description: Get health status of app
      responses:
        default:
          description: Health check response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Server is up!"

  "/api/user/add":
    post:
      summary: Create new user
      tags:
      - User Enrollment
      description: Register user
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/userAddSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: string
                      example: "User enrolled successfully"
                    
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"

  "/api/token":
    post:
      summary: Create access token 
      tags:
      - Access Token
      description: Get access token
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/accessTokenSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: string
                      example: "xxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"
  
  "/api/fees/distance":
    post:
      summary: Get delivery fee according to location distances 
      tags:
      - Delivery Fee
      description: For food delivery
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/deliveryFeeSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: object
                      example: {
                        "deliveryFee": 150
                      }
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"
      security:
      - bearerAuth: []
          
  "/api/fees/distance/courier":
    post:
      summary: Get delivery fee of courier according to location distances 
      tags:
      - Delivery Fee
      description: For courier services
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/deliveryFeeCourierSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: object
                      example: {
                        "deliveryFee": 200
                      }
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"
      security:
      - bearerAuth: []

  "/api/merchant/add":
    post:
      summary: Add merchant 
      tags:
      - Merchant
      description: Add merchant
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/addMerchantSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: string
                      example: "Merchant Added Successfully"
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"
      security:
      - bearerAuth: []

  "/api/merchant/contact/add":
    post:
      summary: Add merchant contact
      tags:
      - Merchant
      description: Add merchant contact
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/addMerchantContactSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: string
                      example: "Merchant Contact Added Successfully"
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"
      security:
      - bearerAuth: []

  "/api/merchant/contact":
    post:
      summary: Get merchant contact list 
      tags:
      - Merchant
      description: Get merchant contact list 
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/merchantContactSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: object
                      example: [
                          {
                              "name": "Ronnie Mesa",
                              "email": "ronnie@alun.app"
                          },
                          {
                              "name": "Achi Maglanque",
                              "email": "achimags@alun.app"
                          }
                      ]
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"
      security:
      - bearerAuth: []

definitions:
  userAddSource:
    properties:
        userType:
          type: string
          example: "internal/external"
        organization:
          type: string
          example: "Prosperna //only required if userType=external"
        username:
          type: string
          example: "username"
        password:
          type: string
          example: "password"

  accessTokenSource:
    properties:
        username:
          type: string
          example: "username"
        password:
          type: string
          example: "password"

  deliveryFeeSource:
    properties:
        deliverFrom:
          type: object
          example: {
            "city": "Nabua",
            "barangay": "San Nicolas (Poblacion)"
          }
        deliverTo:
          type: object
          example: {
            "city": "Baao",
            "barangay": "Santa Isabel"
          }

  deliveryFeeCourierSource:
    properties:
        perishable:
          type: boolean
          example: false
        vehicleType:
          type: string
          example: "motorcycle/tricycle/multicab/private"
        deliverFrom:
          type: object
          example: {
            "city": "Nabua",
            "barangay": "San Nicolas (Poblacion)"
          }
        deliverTo:
          type: object
          example: {
            "city": "Baao",
            "barangay": "Santa Isabel"
          }

  addMerchantSource:
    properties:
        merchantName:
          type: string
          example: "Shawarma Shack"

  addMerchantContactSource:
    properties:
        merchantName:
          type: string
          example: "Desny Grill"
        merchantContact:
          type: object
          example: [
              {
                  "name": "Achi Maglanque",
                  "email": "msg@email.com"
              },
              {
                  "name": "Ronnie Tibak",
                  "email": "neil@email.com"
              }
          ]

  merchantContactSource:
    properties:
        merchantName:
          type: string
          example: "Desny Grill"
  
  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
        example: false
      message:
        type: string
        example: "Error message"
              
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
