openapi: '3.0.0'
info:
  title: 'Alun Delivery API(s)'
  version: '1.0.0'
  description: >-
    Alun Delivery Courier API Documentation. 

paths:
  "/api/health":
    get:
      tags:
      - Monitor Health

      operationId: monitorHealth
      summary: Get health status of app
      description: Get health status of app
      responses:
        default:
          description: Health check response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Server is up!"
      # security:
      # - bearerAuth: []
  
  # "/api/access-token":
  #   post:
  #     summary: get access token 
  #     tags:
  #     - access token
  #     description: get access token
  #     consumes:
  #       - application/json
  #     produces:
  #       - application/json
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "#/definitions/accessTokenSource"
  #     responses:
  #       "200":
  #         description: Success
  #         content:
  #           application/json:
  #               schema:
  #                 type: object
  #                 properties:
  #                   success:
  #                     type: boolean
  #                     example: true
  #                   result:
  #                     type: string
  #                     example: "xxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    
  #       "500":
  #         description: Error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: "#/definitions/ErrorResponse"

  "/api/fees/distance":
    post:
      summary: Get delivery fee according to location distances 
      tags:
      - Delivery Fee
      description: Get delivery fee by distance
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/deliveryFeeSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: object
                      example: {
                        "deliveryFee": 200
                      }
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"

  "/api/merchant/contact":
    post:
      summary: Get merchant contact list 
      tags:
      - Merchant
      description: Get merchant contact list 
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/merchantContactSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: object
                      example: [
                          {
                              "name": "Ronnie Mesa",
                              "email": "ronnie@alun.app"
                          },
                          {
                              "name": "Achi Maglanque",
                              "email": "achimags@alun.app"
                          }
                      ]
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"

definitions:
  merchantContactSource:
    properties:
        merchantName:
          type: string
          example: "Desny Grill"
  deliveryFeeSource:
    properties:
        perishable:
          type: boolean
          example: false
        vahicleType:
          type: string
          example: "motorcycle/tricycle/multicab/private"
        deliverFrom:
          type: object
          example: {
            "city": "Nabua",
            "barangay": "San Nicolas (Poblacion)"
          }
        deliverTo:
          type: object
          example: {
            "city": "Baao",
            "barangay": "Santa Isabel"
          }
  accessTokenSource:
    properties:
        userId:
          type: string
          example: "userId"
        password:
          type: string
          example: "password"
  
  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
        example: false
      message:
        type: string
        example: "Error message"
              
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
