openapi: '3.0.0'
info:
  title: 'Alun Delivery API(s)'
  version: '1.0.0'
  description: >-
    Alun Delivery Courier API Documentation. 

paths:
  
  "/api/access-token":
    post:
      summary: get access token 
      tags:
      - access token
      description: get access token
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/accessTokenSource"
      responses:
        "200":
          description: Success
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: boolean
                      example: true
                    result:
                      type: string
                      example: "xxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/ErrorResponse"

  "/api/health":
    get:
      tags:
      - Monitor Health

      operationId: monitorHealth
      summary: Get health status of app
      description: Get health status of app
      responses:
        default:
          description: Health check response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: string
                    example: "UP"
                  message:
                    type: string
                    example: "Server is up!"
      security:
      - bearerAuth: []
  
definitions:
  
  accessTokenSource:
    properties:
        userId:
          type: string
          example: "userId"
        password:
          type: string
          example: "password"
  
  ErrorResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          type: object
          properties:
            code:
              type: integer
              example: 500
            message:
              type: string
              example: "Error message"
            details:
              type: object
              example: {}
              
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
